# Gaussian Naïve Bayes

In [24]:
import numpy as np
import pandas as pd

dataset = pd.read_csv(r"C:\Users\Dell\Downloads\logit classification.csv")

X = dataset.iloc[:,[2,3]].values
y = dataset.iloc[:,4].values

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

# ❗ No scaling required

from sklearn.naive_bayes import GaussianNB

model = GaussianNB()
model.fit(X_train,y_train)

y_pred = model.predict(X_test)

from sklearn.metrics import accuracy_score, confusion_matrix

print("Accuracy:",accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

Accuracy: 0.925
[[56  2]
 [ 4 18]]


# Bernoulli Naïve Bayes

In [25]:
from sklearn.preprocessing import StandardScaler
from sklearn.naive_bayes import BernoulliNB

# Convert to binary
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

model = BernoulliNB()
model.fit(X_train_bin,y_train)

y_pred = model.predict(X_test_bin)

print("Accuracy:",accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

Accuracy: 0.825
[[55  3]
 [11 11]]


# Multinomial Naïve Bayes

In [27]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.naive_bayes import MultinomialNB

# Make data positive
scaler = MinMaxScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

model = MultinomialNB()
model.fit(X_train_scaled,y_train)

y_pred = model.predict(X_test_scaled)

print("Accuracy:",accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

Accuracy: 0.725
[[58  0]
 [22  0]]
